# Generated by Django 6.0.6 on 2026-07-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tag_task_tags'),
        ('todo', '0002_task_is_deleted'),
    ]

    operations = [
    ]
